import 'dart:io';

void main() {
  final path = r'C:\Users\JIM\my_spots\test\repositories\offline_map_repository_test.dart';
  final content = StringBuffer();
  content.writeln('// Unit tests for OfflineMapRepository.');
  content.writeln('');
  content.writeln("import 'dart:io';");
  content.writeln('');
  content.writeln("import 'package:flutter_test/flutter_test.dart';");
  content.writeln("import 'package:my_spots/models/offline_map.dart';");
  content.writeln("import 'package:my_spots/models/offline_map_layer.dart';");
  content.writeln("import 'package:my_spots/objectbox.g.dart';");
  content.writeln("import 'package:my_spots/repositories/offline_map_repository.dart';");
  content.writeln('');
  content.writeln('OfflineMap _newMap(String uuid, String name) => OfflineMap.create(');
  content.writeln('      uuid: uuid, name: name,');
  content.writeln('      northLat: 44.0, southLat: 43.0,');
  content.writeln('      westLng: 6.0, eastLng: 7.5,');
  content.writeln('    );');
  content.writeln('');
  content.writeln('OfflineMapLayer _newLayer(LayerType t, int zmin, int zmax) =>');
  content.writeln('    OfflineMapLayer.create(layerType: t, minZoom: zmin, maxZoom: zmax);');
  content.writeln('');
  content.writeln('void main() {');
  content.writeln('  late Directory tmpDir;');
  content.writeln('  late Store store;');
  content.writeln('  late OfflineMapRepository repo;');
  content.writeln('');
  content.writeln('  setUp(() async {');
  content.writeln("    tmpDir = await Directory.systemTemp.createTemp('offline_map_test_');");
  content.writeln('    store = await openStore(directory: tmpDir.path);');
  content.writeln('    repo = OfflineMapRepository(store);');
  content.writeln('  });');
  content.writeln('');
  content.writeln('  tearDown(() async {');
  content.writeln('    store.close();');
  content.writeln('    if (await tmpDir.exists()) {');
  content.writeln('      await tmpDir.delete(recursive: true);');
  content.writeln('    }');
  content.writeln('  });');
  content.writeln('');
  content.writeln('  group("OfflineMap CRUD", () {');
  content.writeln('    test("save assigns a new id and findById retrieves it", () {');
  content.writeln('      final saved = repo.save(_newMap("uuid-1", "Cote"));');
  content.writeln('      expect(saved.id, isNot(0));');
  content.writeln('      final fetched = repo.findById(saved.id);');
  content.writeln('      expect(fetched, isNotNull);');
  content.writeln('      expect(fetched!.uuid, "uuid-1");');
  content.writeln('      expect(fetched.name, "Cote");');
  content.writeln('      expect(fetched.status, OfflineMapStatus.notStarted);');
  content.writeln('      expect(fetched.isNotStarted, isTrue);');
  content.writeln('      expect(fetched.isCompleted, isFalse);');
  content.writeln('    });');
  content.writeln('  });');
  content.writeln('}');
  File(path).writeAsStringSync(content.toString());
  print('Wrote part 1: ${content.length} chars');
}
