import 'dart:io';

void main() {
  final path = r'C:\Users\JIM\my_spots\test\services\map_tile_cache_service_test.dart';
  final sb = StringBuffer();

  sb.writeln('// Unit tests for MapTileCacheService — zone-scoped FMTC store management.');
  sb.writeln('//');
  sb.writeln('// Coverage:');
  sb.writeln('// - Store naming per zone (marine + LiDAR)');
  sb.writeln('// - deleteStoresForZone uses only public FMTC API');
  sb.writeln('// - Graceful handling of absent stores (no throw on delete)');
  sb.writeln('');
  sb.writeln("import 'package:flutter_test/flutter_test.dart';");
  sb.writeln("import 'package:flutter_map_tile_caching/flutter_map_tile_caching.dart';");
  sb.writeln("import 'package:my_spots/services/map_tile_cache_service.dart';");
  sb.writeln('');
  sb.writeln('void main() {');
  sb.writeln('  group("Zone store naming — marine", () {');
  sb.writeln(r'    test("store name follows pattern marine_zone_$uuid", () {');
  sb.writeln('      const zoneUuid = "550e8400-e29b-41d4-a716-446655440000";');
  sb.writeln('      final store = MapTileCacheService.marineStoreForZone(zoneUuid);');
  sb.writeln('      expect(store.storeName, "marine_zone_550e8400-e29b-41d4-a716-446655440000");');
  sb.writeln('    });');
  sb.writeln();
  sb.writeln('    test("different uuids produce different store names", () {');
  sb.writeln('      final s1 = MapTileCacheService.marineStoreForZone("zone-aaaa");');
  sb.writeln('      final s2 = MapTileCacheService.marineStoreForZone("zone-bbbb");');
  sb.writeln('      expect(s1.storeName, isNot(s2.storeName));');
  sb.writeln('      expect(s1.storeName, endsWith("zone-aaaa"));');
  sb.writeln('      expect(s2.storeName, endsWith("zone-bbbb"));');
  sb.writeln('    });');
  sb.writeln();
  sb.writeln('    test("uuid with special characters is embedded verbatim", () {');
  sb.writeln('      final store = MapTileCacheService.marineStoreForZone("my-map-01");');
  sb.writeln('      expect(store.storeName, "marine_zone_my-map-01");');
  sb.writeln('    });');
  sb.writeln();
  sb.writeln('    test("returned object is an FMTCStore instance", () {');
  sb.writeln('      final store = MapTileCacheService.marineStoreForZone("test-zone");');
  sb.writeln('      expect(store, isA<FMTCStore>());');
  sb.writeln('    });');
  sb.writeln('  });');
  sb.writeln();
  sb.writeln('  group("Zone store naming — lidar", () {');
  sb.writeln(r'    test("store name follows pattern lidar_zone_$uuid", () {');
  sb.writeln('      const zoneUuid = "660e8400-e29b-41d4-a716-446655440001";');
  sb.writeln('      final store = MapTileCacheService.lidarStoreForZone(zoneUuid);');
  sb.writeln('      expect(store.storeName, "lidar_zone_660e8400-e29b-41d4-a716-446655440001");');
  sb.writeln('    });');
  sb.writeln();
  sb.writeln('    test("marine and lidar stores for same zone are distinct", () {');
  sb.writeln('      const zoneUuid = "same-zone-uuid";');
  sb.writeln('      final marine = MapTileCacheService.marineStoreForZone(zoneUuid);');
  sb.writeln('      final lidar = MapTileCacheService.lidarStoreForZone(zoneUuid);');
  sb.writeln('      expect(marine.storeName, isNot(lidar.storeName));');
  sb.writeln('      expect(marine.storeName, startsWith("marine_zone_"));');
  sb.writeln('      expect(lidar.storeName, startsWith("lidar_zone_"));');
  sb.writeln('    });');
  sb.writeln();
  sb.writeln('    test("returned object is an FMTCStore instance", () {');
  sb.writeln('      final store = MapTileCacheService.lidarStoreForZone("test-zone");');
  sb.writeln('      expect(store, isA<FMTCStore>());');
  sb.writeln('    });');
  sb.writeln('  });');
  sb.writeln();
  sb.writeln('  group("deleteStoresForZone — public FMTC API compliance", () {');
  sb.writeln('    // NOTE: We test that the method does NOT throw on absent stores.');
  sb.writeln('    // This validates the try/catch around manage.delete() — the public');
  sb.writeln('    // FMTC API. We use a guaranteed-unique store name so there is zero');
  sb.writeln('    // risk of accidentally deleting real data.');
  sb.writeln('    //');
  sb.writeln('    // Even if FMTC is not initialised, manage.delete() throws');
  sb.writeln('    // RootUnavailable, which our catch-all block handles silently.');
  sb.writeln();
  sb.writeln('    test("does not throw when called on non-existent zone", () async {');
  sb.writeln('      // Use a uuid that has zero chance of existing');
  sb.writeln('      const nonExistentZone = "delete-test-zone-00000000-0000-0000-0000-000000000000";');
  sb.writeln('      // Must not throw');
  sb.writeln('      await MapTileCacheService.deleteStoresForZone(nonExistentZone);');
  sb.writeln('    });');
  sb.writeln();
  sb.writeln('    test("calling twice on same zone does not throw", () async {');
  sb.writeln('      const zone = "delete-test-zone-11111111-1111-1111-1111-111111111111";');
  sb.writeln('      await MapTileCacheService.deleteStoresForZone(zone);');
  sb.writeln('      await MapTileCacheService.deleteStoresForZone(zone);');
  sb.writeln('      // If we get here, no exception propagated');
  sb.writeln('    });');
  sb.writeln('  });');
  sb.writeln('}');

  File(path).writeAsStringSync(sb.toString());
  print('Written: $path (${sb.length} chars)');
}
