import 'dart:io';

void main() {
  final path = r'C:\Users\JIM\my_spots\lib\services\zone_download_service.dart';
  final sb = StringBuffer();

  sb.writeln('');
  sb.writeln('    try {');
  sb.writeln('      for (var i = 0; i < layers.length; i++) {');
  sb.writeln('        if (state.isCancelled) break;');
  sb.writeln('        final layer = layers[i];');
  sb.writeln('        final label = layer.layerType.name;');
  sb.writeln('');
  sb.writeln('        void emitProgress(double p) {');
  sb.writeln('          final globalRatio = (i + p) / layers.length;');
  sb.writeln('          onProgress?.call(');
  sb.writeln('            progress: globalRatio.clamp(0.0, 1.0),');
  sb.writeln('            layerLabel: label,');
  sb.writeln('          );');
  sb.writeln('        }');
  sb.writeln('        // Emit initial tick so the UI updates immediately.');
  sb.writeln('        emitProgress(0.0);');
  sb.writeln('');
  sb.writeln('        LayerDownloadResult result;');
  sb.writeln('        try {');
  sb.writeln('          result = await _downloader.downloadLayer(');
  sb.writeln('            zoneUuid: map.uuid,');
  sb.writeln('            store: storeForLayerType(map.uuid, layer.layerType),');
  sb.writeln('            urlTemplate: urlForLayerType(layer.layerType),');
  sb.writeln('            bounds: bounds,');
  sb.writeln('            minZoom: layer.minZoom,');
  sb.writeln('            maxZoom: layer.maxZoom,');
  sb.writeln('            headers: shomHeaders(),');
  sb.writeln('            onProgress: emitProgress,');
  sb.writeln('          );');
  sb.writeln('        } catch (e) {');
  sb.writeln('          // Treat exceptions as failures but keep going for other layers.');
  sb.writeln('          layer.downloadStatus = LayerDownloadStatus.failed;');
  sb.writeln('          repository.saveLayer(map, layer);');
  sb.writeln('          state.failedLayers++;');
  sb.writeln('          continue;');
  sb.writeln('        }');
  sb.writeln('');
  sb.writeln('        layer.downloadedTileCount = result.downloadedTileCount;');
  sb.writeln('        layer.estimatedTileCount = result.estimatedTileCount;');
  sb.writeln('        layer.downloadStatus = result.successful');
  sb.writeln('            ? LayerDownloadStatus.completed');
  sb.writeln('            : LayerDownloadStatus.failed;');
  sb.writeln('        repository.saveLayer(map, layer);');
  sb.writeln('');
  sb.writeln('        if (result.successful) {');
  sb.writeln('          state.completedLayers++;');
  sb.writeln('        } else {');
  sb.writeln('          state.failedLayers++;');
  sb.writeln('        }');
  sb.writeln('        onProgress?.call(');
  sb.writeln('          progress: (i + 1) / layers.length,');
  sb.writeln('          layerLabel: label,');
  sb.writeln('        );');
  sb.writeln('      }');
  sb.writeln('    } finally {');
  sb.writeln('      _finalizeZone(map, state);');
  sb.writeln('      _zones.remove(map.uuid);');
  sb.writeln('    }');
  sb.writeln('  }');
  sb.writeln('');
  sb.writeln('  void _finalizeZone(OfflineMap map, _ZoneState state) {');
  sb.writeln('    if (state.isCancelled) {');
  sb.writeln('      map.status = OfflineMapStatus.failed;');
  sb.writeln('      repository.save(map);');
  sb.writeln('      return;');
  sb.writeln('    }');
  sb.writeln('    if (state.failedLayers == 0) {');
  sb.writeln('      map.status = OfflineMapStatus.ready;');
  sb.writeln('      map.completedAt = DateTime.now();');
  sb.writeln('    } else if (state.completedLayers == 0) {');
  sb.writeln('      map.status = OfflineMapStatus.failed;');
  sb.writeln('    } else {');
  sb.writeln('      map.status = OfflineMapStatus.partial;');
  sb.writeln('      map.completedAt = DateTime.now();');
  sb.writeln('    }');
  sb.writeln('    repository.save(map);');
  sb.writeln('  }');
  sb.writeln('');
  sb.writeln('  /// Cancels the in-flight download for [zoneUuid]. No-op if inactive.');
  sb.writeln('  Future<void> cancelDownload(String zoneUuid) async {');
  sb.writeln('    final state = _zones[zoneUuid];');
  sb.writeln('    if (state == null) return;');
  sb.writeln('    state.isCancelled = true;');
  sb.writeln('    await _downloader.cancel(zoneUuid);');
  sb.writeln('  }');
  sb.writeln('');
  sb.writeln('  /// Pauses the download for [zoneUuid] (no-op if not downloading).');
  sb.writeln('  void pauseDownload(String zoneUuid) {');
  sb.writeln('    _downloader.pause(zoneUuid);');
  sb.writeln('  }');
  sb.writeln('');
  sb.writeln('  /// Resumes a paused download for [zoneUuid] (no-op if not paused).');
  sb.writeln('  void resumeDownload(String zoneUuid) {');
  sb.writeln('    _downloader.resume(zoneUuid);');
  sb.writeln('  }');
  sb.writeln('}');

  File(path).writeAsStringSync(
    File(path).readAsStringSync() + sb.toString(),
    flush: true,
  );
  print('Part 3b appended: +${sb.length} chars');
}
