import 'dart:io';

void main() {
  final path = r'C:\Users\JIM\my_spots\lib\services\zone_download_service.dart';
  final sb = StringBuffer();

  sb.writeln("import 'dart:async';");
  sb.writeln('');
  sb.writeln("import 'package:flutter_map/flutter_map.dart';");
  sb.writeln("import 'package:flutter_map_tile_caching/flutter_map_tile_caching.dart';");
  sb.writeln("import 'package:latlong2/latlong.dart';");
  sb.writeln("import 'package:my_spots/models/offline_map.dart';");
  sb.writeln("import 'package:my_spots/models/offline_map_layer.dart';");
  sb.writeln("import 'package:my_spots/repositories/offline_map_repository.dart';");
  sb.writeln("import 'package:my_spots/services/map_tile_cache_service.dart';");
  sb.writeln("import 'package:my_spots/services/marine_map_service.dart';");
  sb.writeln('');
  sb.writeln('/// Per-zone progress callback.');
  sb.writeln('typedef ZoneProgressCallback = void Function({');
  sb.writeln('  required double progress,');
  sb.writeln('  required String layerLabel,');
  sb.writeln('});');
  sb.writeln('');
  sb.writeln('/// Result of a single-layer bulk download.');
  sb.writeln('class LayerDownloadResult {');
  sb.writeln('  const LayerDownloadResult({');
  sb.writeln('    required this.downloadedTileCount,');
  sb.writeln('    required this.estimatedTileCount,');
  sb.writeln('    required this.successful,');
  sb.writeln('  });');
  sb.writeln('  final int downloadedTileCount;');
  sb.writeln('  final int estimatedTileCount;');
  sb.writeln('  final bool successful;');
  sb.writeln('}');
  sb.writeln('');
  sb.writeln('/// FMTC layer downloader abstraction (for unit-testability).');
  sb.writeln('abstract class LayerDownloader {');
  sb.writeln('  Future<LayerDownloadResult> downloadLayer({');
  sb.writeln('    required String zoneUuid,');
  sb.writeln('    required FMTCStore store,');
  sb.writeln('    required String urlTemplate,');
  sb.writeln('    required LatLngBounds bounds,');
  sb.writeln('    required int minZoom,');
  sb.writeln('    required int maxZoom,');
  sb.writeln('    required Map<String, String> headers,');
  sb.writeln('    required void Function(double progress) onProgress,');
  sb.writeln('  });');
  sb.writeln('  Future<void> cancel(String zoneUuid);');
  sb.writeln('  void pause(String zoneUuid);');
  sb.writeln('  void resume(String zoneUuid);');
  sb.writeln('}');
  sb.writeln('');
  sb.writeln('/// Production [LayerDownloader] backed by FMTC v10 public API.');
  sb.writeln('class FmtcLayerDownloader implements LayerDownloader {');
  sb.writeln('  const FmtcLayerDownloader();');
  sb.writeln('');
  sb.writeln('  @override');
  sb.writeln('  Future<LayerDownloadResult> downloadLayer({');
  sb.writeln('    required String zoneUuid,');
  sb.writeln('    required FMTCStore store,');
  sb.writeln('    required String urlTemplate,');
  sb.writeln('    required LatLngBounds bounds,');
  sb.writeln('    required int minZoom,');
  sb.writeln('    required int maxZoom,');
  sb.writeln('    required Map<String, String> headers,');
  sb.writeln('    required void Function(double progress) onProgress,');
  sb.writeln('  }) async {');
  sb.writeln('    final region = RectangleRegion(bounds).toDownloadable(');
  sb.writeln('      minZoom: minZoom,');
  sb.writeln('      maxZoom: maxZoom,');
  sb.writeln('      options: TileLayer(');
  sb.writeln('        urlTemplate: urlTemplate,');
  sb.writeln('        userAgentPackageName: MapTileCacheService.packageName,');
  sb.writeln('        tileProvider: const NoTileProvider(),');
  sb.writeln('        headers: headers,');
  sb.writeln('      ),');
  sb.writeln('    );');
  sb.writeln('');
  sb.writeln('    final streams = store.download.startForeground(');
  sb.writeln('      region: region,');
  sb.writeln('      instanceId: zoneUuid,');
  sb.writeln('      disableRecovery: true,');
  sb.writeln('    );');
  sb.writeln('');
  sb.writeln('    var maxTiles = 0;');
  sb.writeln('    var successful = 0;');
  sb.writeln('    var failed = 0;');
  sb.writeln('');
  sb.writeln('    await for (final p in streams.downloadProgress) {');
  sb.writeln('      maxTiles = p.maxTilesCount;');
  sb.writeln('      successful = p.successfulTilesCount;');
  sb.writeln('      failed = p.failedRequestTilesCount + p.negativeResponseTilesCount;');
  sb.writeln('      if (maxTiles > 0) {');
  sb.writeln('        onProgress((p.attemptedTilesCount / maxTiles).clamp(0.0, 1.0));');
  sb.writeln('      }');
  sb.writeln('    }');
  sb.writeln('');
  sb.writeln('    return LayerDownloadResult(');
  sb.writeln('      downloadedTileCount: successful,');
  sb.writeln('      estimatedTileCount: maxTiles > 0 ? maxTiles : (successful + failed),');
  sb.writeln('      successful: failed == 0,');
  sb.writeln('    );');
  sb.writeln('  }');
  sb.writeln('');
  sb.writeln('  @override');
  sb.writeln('  Future<void> cancel(String zoneUuid) async {');
  sb.writeln("    await FMTCStore('').download.cancel(instanceId: zoneUuid);");
  sb.writeln('  }');
  sb.writeln('');
  sb.writeln('  @override');
  sb.writeln('  void pause(String zoneUuid) {');
  sb.writeln("    FMTCStore('').download.pause(instanceId: zoneUuid);");
  sb.writeln('  }');
  sb.writeln('');
  sb.writeln('  @override');
  sb.writeln('  void resume(String zoneUuid) {');
  sb.writeln("    FMTCStore('').download.resume(instanceId: zoneUuid);");
  sb.writeln('  }');
  sb.writeln('}');

  File(path).writeAsStringSync(sb.toString());
  print('Part 1 written: ${sb.length} chars');
}
