import 'dart:io';

void main() {
  final path = r'C:\Users\JIM\my_spots\test\services\zone_download_service_test.dart';
  final sb = StringBuffer();

  sb.writeln('// Unit tests for ZoneDownloadService.');
  sb.writeln('//');
  sb.writeln('// Tests cover:');
  sb.writeln('// - downloadZone sets initial downloading state');
  sb.writeln('// - Successful layer → status=completed, tile count updated');
  sb.writeln('// - Failed layer → status=failed, counter incremented');
  sb.writeln('// - Cancel mid-download → status=failed');
  sb.writeln('// - All layers success → map status=ready');
  sb.writeln('// - Mixed results → map status=partial');
  sb.writeln('// - Empty layers list → no-op');
  sb.writeln('// - isDownloading / activeCount state tracking');
  sb.writeln('// - URL and store selection per layer type');
  sb.writeln('');
  sb.writeln("import 'dart:async';");
  sb.writeln("import 'dart:io';");
  sb.writeln('');
  sb.writeln("import 'package:flutter_map/flutter_map.dart';");
  sb.writeln("import 'package:flutter_map_tile_caching/flutter_map_tile_caching.dart';");
  sb.writeln("import 'package:flutter_test/flutter_test.dart';");
  sb.writeln("import 'package:my_spots/models/offline_map.dart';");
  sb.writeln("import 'package:my_spots/models/offline_map_layer.dart';");
  sb.writeln("import 'package:my_spots/objectbox.g.dart';");
  sb.writeln("import 'package:my_spots/repositories/offline_map_repository.dart';");
  sb.writeln("import 'package:my_spots/services/zone_download_service.dart';");
  sb.writeln('');
  sb.writeln('/// Call record for [FakeLayerDownloader].');
  sb.writeln('class _DownloadCall {');
  sb.writeln('  _DownloadCall({');
  sb.writeln('    required this.zoneUuid,');
  sb.writeln('    required this.storeName,');
  sb.writeln('    required this.url,');
  sb.writeln('    required this.minZoom,');
  sb.writeln('    required this.maxZoom,');
  sb.writeln('  });');
  sb.writeln('  final String zoneUuid;');
  sb.writeln('  final String storeName;');
  sb.writeln('  final String url;');
  sb.writeln('  final int minZoom;');
  sb.writeln('  final int maxZoom;');
  sb.writeln('}');
  sb.writeln('');
  sb.writeln('/// Fake downloader: records calls, returns configured results, supports cancel.');
  sb.writeln('class FakeLayerDownloader implements LayerDownloader {');
  sb.writeln('  FakeLayerDownloader({this.results = const [], this.cancelError});');
  sb.writeln('  final List<LayerDownloadResult> results;');
  sb.writeln('  final Object? cancelError;');
  sb.writeln('  final calls = <_DownloadCall>[];');
  sb.writeln('  String? cancelledZone;');
  sb.writeln('  int downloadCallCount = 0;');
  sb.writeln('');
  sb.writeln('  @override');
  sb.writeln('  Future<LayerDownloadResult> downloadLayer({');
  sb.writeln('    required String zoneUuid,');
  sb.writeln('    required FMTCStore store,');
  sb.writeln('    required String urlTemplate,');
  sb.writeln('    required LatLngBounds bounds,');
  sb.writeln('    required int minZoom,');
  sb.writeln('    required int maxZoom,');
  sb.writeln('    required Map<String, String> headers,');
  sb.writeln('    required void Function(double) onProgress,');
  sb.writeln('  }) async {');
  sb.writeln('    calls.add(_DownloadCall(');
  sb.writeln('      zoneUuid: zoneUuid,');
  sb.writeln('      storeName: store.storeName,');
  sb.writeln('      url: urlTemplate,');
  sb.writeln('      minZoom: minZoom,');
  sb.writeln('      maxZoom: maxZoom,');
  sb.writeln('    ));');
  sb.writeln('    downloadCallCount++;');
  sb.writeln('    onProgress(1.0);');
  sb.writeln('    if (downloadCallCount <= results.length) {');
  sb.writeln('      return results[downloadCallCount - 1];');
  sb.writeln('    }');
  sb.writeln('    return const LayerDownloadResult(');
  sb.writeln('      downloadedTileCount: 0, estimatedTileCount: 0, successful: true);');
  sb.writeln('  }');
  sb.writeln('');
  sb.writeln('  @override');
  sb.writeln('  Future<void> cancel(String zoneUuid) async {');
  sb.writeln('    cancelledZone = zoneUuid;');
  sb.writeln('    if (cancelError != null) throw cancelError;');
  sb.writeln('  }');
  sb.writeln('');
  sb.writeln('  @override');
  sb.writeln('  void pause(String zoneUuid) {}');
  sb.writeln('');
  sb.writeln('  @override');
  sb.writeln('  void resume(String zoneUuid) {}');
  sb.writeln('}');
  sb.writeln('');
  sb.writeln('OfflineMap _newMap(String uuid) => OfflineMap.create(');
  sb.writeln('  uuid: uuid, name: \'Test Zone\',');
  sb.writeln('  northLat: 44.0, southLat: 43.0, westLng: 6.0, eastLng: 7.5,');
  sb.writeln(');');
  sb.writeln('');
  sb.writeln('OfflineMapLayer _newLayer(LayerType t) => OfflineMapLayer.create(');
  sb.writeln('  layerType: t, minZoom: 8, maxZoom: 14,');
  sb.writeln(');');
  sb.writeln('');
  sb.writeln('void main() {');
  sb.writeln('  late Directory tmpDir;');
  sb.writeln('  late Store store;');
  sb.writeln('  late OfflineMapRepository repo;');
  sb.writeln('');
  sb.writeln('  setUp(() async {');
  sb.writeln('    tmpDir = await Directory.systemTemp.createTemp(\'zds_test_\');');
  sb.writeln('    store = await openStore(directory: tmpDir.path);');
  sb.writeln('    repo = OfflineMapRepository(store);');
  sb.writeln('  });');
  sb.writeln('');
  sb.writeln('  tearDown(() async {');
  sb.writeln('    store.close();');
  sb.writeln('    if (await tmpDir.exists()) await tmpDir.delete(recursive: true);');
  sb.writeln('  });');

  File(path).writeAsStringSync(sb.toString());
  print('Part 1: ${sb.length} chars');
}
