import 'dart:io';

void main() {
  final path = r'C:\Users\JIM\my_spots\test\services\zone_download_service_test.dart';
  final lines = <String>[];

  void w(String s) => lines.add(s);

  w('// Unit tests for ZoneDownloadService — zone-scoped FMTC download orchestration.');
  w('');
  w("import 'dart:async';");
  w("import 'dart:io';");
  w("import 'package:flutter_map/flutter_map.dart';");
  w("import 'package:flutter_map_tile_caching/flutter_map_tile_caching.dart';");
  w("import 'package:flutter_test/flutter_test.dart';");
  w("import 'package:my_spots/models/offline_map.dart';");
  w("import 'package:my_spots/models/offline_map_layer.dart';");
  w("import 'package:my_spots/objectbox.g.dart';");
  w("import 'package:my_spots/repositories/offline_map_repository.dart';");
  w("import 'package:my_spots/services/zone_download_service.dart';");
  w('');
  w('/// Record of a downloadLayer() call (for test assertions).');
  w('class _Call {');
  w('  _Call({required this.zoneUuid, required this.storeName, required this.url,');
  w('       required this.minZoom, required this.maxZoom});');
  w('  final String zoneUuid, storeName, url;');
  w('  final int minZoom, maxZoom;');
  w('}');
  w('');
  w('/// Fake [LayerDownloader] that records calls and returns configurable results.');
  w('class FakeLayerDownloader implements LayerDownloader {');
  w('  FakeLayerDownloader({this.results = const [], this.cancelError});');
  w('  final List<LayerDownloadResult> results;');
  w('  final Object? cancelError;');
  w('  final calls = <_Call>[];');
  w('  String? cancelledZone;');
  w('  int count = 0;');
  w('  @override');
  w('  Future<LayerDownloadResult> downloadLayer({');
  w('    required String zoneUuid, required FMTCStore store,');
  w('    required String urlTemplate, required LatLngBounds bounds,');
  w('    required int minZoom, required int maxZoom,');
  w('    required Map<String, String> headers,');
  w('    required void Function(double) onProgress,');
  w('  }) async {');
  w('    calls.add(_Call(zoneUuid: zoneUuid, storeName: store.storeName,');
  w('        url: urlTemplate, minZoom: minZoom, maxZoom: maxZoom));');
  w('    count++;');
  w('    onProgress(1.0);');
  w('    if (count <= results.length) return results[count - 1];');
  w('    return const LayerDownloadResult(downloadedTileCount: 0, estimatedTileCount: 0, successful: true);');
  w('  }');
  w('  @override');
  w('  Future<void> cancel(String zoneUuid) async {');
  w('    cancelledZone = zoneUuid;');
  w('    if (cancelError != null) throw cancelError;');
  w('  }');
  w('  @override void pause(String z) {}');
  w('  @override void resume(String z) {}');
  w('}');
  w('');
  w('OfflineMap _m(String u) => OfflineMap.create(uuid: u, name: \'Z\', northLat: 44, southLat: 43, westLng: 6, eastLng: 7);');
  w('OfflineMapLayer _l(LayerType t) => OfflineMapLayer.create(layerType: t, minZoom: 8, maxZoom: 14);');
  w('');
  w('void main() {');
  w('  late Directory tmp; late Store st; late OfflineMapRepository repo;');
  w('  setUp(() async {');
  w('    tmp = await Directory.systemTemp.createTemp(\'zds_t_\');');
  w('    st = await openStore(directory: tmp.path);');
  w('    repo = OfflineMapRepository(st);');
  w('  });');
  w('  tearDown(() async {');
  w('    st.close();');
  w('    if (await tmp.exists()) await tmp.delete(recursive: true);');
  w('  });');

  File(path).writeAsStringSync(lines.join('\n'));
  print('Part A: ${lines.length} lines');
}
