import 'dart:io';

void main() {
  final path = r'C:\Users\JIM\my_spots\test\services\zone_download_service_test.dart';
  final lines = <String>[];

  void w(String s) => lines.add(s);

  w('');
  w("  group('downloadZone — empty input', () {");
  w("    test('empty layers list returns without calling downloader', () async {");
  w("      final d = FakeLayerDownloader();");
  w("      final s = ZoneDownloadService(repository: repo, downloader: d);");
  w("      final map = repo.save(_m('empty'));");
  w("      await s.downloadZone(map: map, layers: []);");
  w("      expect(d.count, 0);");
  w("    });");
  w("  });");
  w('');
  w("  group('downloadZone — initial state', () {");
  w("    test('sets map status to downloading before completion', () async {");
  w("      final d = FakeLayerDownloader();");
  w("      final s = ZoneDownloadService(repository: repo, downloader: d);");
  w("      final map = repo.save(_m('init-map'));");
  w("      final layer = repo.saveLayer(map, _l(LayerType.marine25k));");
  w("      unawaited(s.downloadZone(map: map, layers: [layer]));");
  w("      await Future.delayed(Duration.zero);");
  w("      expect(repo.findByUuid(map.uuid)!.status, OfflineMapStatus.downloading);");
  w("      await s.cancelDownload(map.uuid);");
  w("    });");
  w("    test('sets all layer statuses to downloading', () async {");
  w("      final d = FakeLayerDownloader();");
  w("      final s = ZoneDownloadService(repository: repo, downloader: d);");
  w("      final map = repo.save(_m('init-layers'));");
  w("      final a = repo.saveLayer(map, _l(LayerType.marine25k));");
  w("      final b = repo.saveLayer(map, _l(LayerType.lidarOmbrage));");
  w("      unawaited(s.downloadZone(map: map, layers: [a, b]));");
  w("      await Future.delayed(Duration.zero);");
  w("      expect(repo.findLayerById(a.id)!.downloadStatus, LayerDownloadStatus.downloading);");
  w("      expect(repo.findLayerById(b.id)!.downloadStatus, LayerDownloadStatus.downloading);");
  w("      await s.cancelDownload(map.uuid);");
  w("    });");
  w("  });");
  w('');
  w("  group('downloadZone — completion states', () {");
  w("    test('all layers successful → map status ready', () async {");
  w("      final d = FakeLayerDownloader(results: [");
  w("        const LayerDownloadResult(downloadedTileCount: 100, estimatedTileCount: 100, successful: true),");
  w("        const LayerDownloadResult(downloadedTileCount: 50, estimatedTileCount: 50, successful: true),");
  w("      ]);");
  w("      final s = ZoneDownloadService(repository: repo, downloader: d);");
  w("      final map = repo.save(_m('all-ok'));");
  w("      final a = repo.saveLayer(map, _l(LayerType.marine25k));");
  w("      final b = repo.saveLayer(map, _l(LayerType.lidarOmbrage));");
  w("      await s.downloadZone(map: map, layers: [a, b]);");
  w("      final u = repo.findByUuid(map.uuid)!;");
  w("      expect(u.status, OfflineMapStatus.ready);");
  w("      expect(u.completedAt.millisecondsSinceEpoch, greaterThan(0));");
  w("      expect(repo.findLayerById(a.id)!.downloadStatus, LayerDownloadStatus.completed);");
  w("      expect(repo.findLayerById(b.id)!.downloadStatus, LayerDownloadStatus.completed);");
  w("    });");
  w("    test('all layers failed → map status failed', () async {");
  w("      final d = FakeLayerDownloader(results: [");
  w("        const LayerDownloadResult(downloadedTileCount: 0, estimatedTileCount: 100, successful: false),");
  w("        const LayerDownloadResult(downloadedTileCount: 0, estimatedTileCount: 50, successful: false),");
  w("      ]);");
  w("      final s = ZoneDownloadService(repository: repo, downloader: d);");
  w("      final map = repo.save(_m('all-fail'));");
  w("      final a = repo.saveLayer(map, _l(LayerType.marine25k));");
  w("      final b = repo.saveLayer(map, _l(LayerType.lidarOmbrage));");
  w("      await s.downloadZone(map: map, layers: [a, b]);");
  w("      expect(repo.findByUuid(map.uuid)!.status, OfflineMapStatus.failed);");
  w("    });");
  w("    test('mixed results → map status partial', () async {");
  w("      final d = FakeLayerDownloader(results: [");
  w("        const LayerDownloadResult(downloadedTileCount: 100, estimatedTileCount: 100, successful: true),");
  w("        const LayerDownloadResult(downloadedTileCount: 0, estimatedTileCount: 50, successful: false),");
  w("      ]);");
  w("      final s = ZoneDownloadService(repository: repo, downloader: d);");
  w("      final map = repo.save(_m('partial'));");
  w("      final a = repo.saveLayer(map, _l(LayerType.marine25k));");
  w("      final b = repo.saveLayer(map, _l(LayerType.lidarOmbrage));");
  w("      await s.downloadZone(map: map, layers: [a, b]);");
  w("      final u = repo.findByUuid(map.uuid)!;");
  w("      expect(u.status, OfflineMapStatus.partial);");
  w("      expect(u.completedAt.millisecondsSinceEpoch, greaterThan(0));");
  w("    });");
  w("    test('successful layer records tile counts in ObjectBox', () async {");
  w("      final d = FakeLayerDownloader(results: [");
  w("        const LayerDownloadResult(downloadedTileCount: 42, estimatedTileCount: 100, successful: true),");
  w("      ]);");
  w("      final s = ZoneDownloadService(repository: repo, downloader: d);");
  w("      final map = repo.save(_m('tile-count'));");
  w("      final layer = repo.saveLayer(map, _l(LayerType.marine25k));");
  w("      await s.downloadZone(map: map, layers: [layer]);");
  w("      final u = repo.findLayerById(layer.id)!;");
  w("      expect(u.downloadedTileCount, 42);");
  w("      expect(u.estimatedTileCount, 100);");
  w("    });");
  w("  });");

  File(path).writeAsStringSync(
    File(path).readAsStringSync() + '\n' + lines.join('\n'),
    flush: true,
  );
  print('Part B: ${lines.length} lines');
}
