import 'dart:io';
void main() {
  final p = r'C:\Users\JIM\my_spots\test\services\zone_download_service_test.dart';
  final s = StringBuffer();
  s.writeln('// Unit tests for ZoneDownloadService — zone-scoped FMTC download orchestration.');
  s.writeln("import 'dart:async';");
  s.writeln("import 'dart:io';");
  s.writeln("import 'package:flutter_map/flutter_map.dart';");
  s.writeln("import 'package:flutter_map_tile_caching/flutter_map_tile_caching.dart';");
  s.writeln("import 'package:flutter_test/flutter_test.dart';");
  s.writeln("import 'package:my_spots/models/offline_map.dart';");
  s.writeln("import 'package:my_spots/models/offline_map_layer.dart';");
  s.writeln("import 'package:my_spots/objectbox.g.dart';");
  s.writeln("import 'package:my_spots/repositories/offline_map_repository.dart';");
  s.writeln("import 'package:my_spots/services/zone_download_service.dart';");
  s.writeln('');
  s.writeln('class _Call { _Call({required this.z, required this.sn, required this.u, required this.zmin, required this.zmax}); final String z, sn, u; final int zmin, zmax; }');
  s.writeln('class FakeLayerDownloader implements LayerDownloader {');
  s.writeln('  FakeLayerDownloader({this.results = const [], this.cancelError});');
  s.writeln('  final List<LayerDownloadResult> results; final Object? cancelError;');
  s.writeln('  final calls = <_Call>[]; String? cancelledZone; int count = 0;');
  s.writeln('  @override Future<LayerDownloadResult> downloadLayer({');
  s.writeln('    required String zoneUuid, required FMTCStore store, required String urlTemplate,');
  s.writeln('    required LatLngBounds bounds, required int minZoom, required int maxZoom,');
  s.writeln('    required Map<String, String> headers, required void Function(double) onProgress,}) async {');
  s.writeln('    calls.add(_Call(z: zoneUuid, sn: store.storeName, u: urlTemplate, zmin: minZoom, zmax: maxZoom));');
  s.writeln('    count++; onProgress(1.0);');
  s.writeln('    if (count <= results.length) return results[count - 1];');
  s.writeln('    return const LayerDownloadResult(downloadedTileCount: 0, estimatedTileCount: 0, successful: true);');
  s.writeln('  }');
  s.writeln('  @override Future<void> cancel(String zoneUuid) async { cancelledZone = zoneUuid; if (cancelError != null) throw cancelError; }');
  s.writeln('  @override void pause(String z) {} @override void resume(String z) {}');
  s.writeln('}');
  s.writeln('OfflineMap _m(String u) => OfflineMap.create(uuid: u, name: \'Z\', northLat: 44, southLat: 43, westLng: 6, eastLng: 7);');
  s.writeln('OfflineMapLayer _l(LayerType t) => OfflineMapLayer.create(layerType: t, minZoom: 8, maxZoom: 14);');
  s.writeln('void main() { late Directory tmp; late Store st; late OfflineMapRepository repo;');
  s.writeln('  setUp(() async { tmp = await Directory.systemTemp.createTemp(\'zds_t_\'); st = await openStore(directory: tmp.path); repo = OfflineMapRepository(st); });');
  s.writeln('  tearDown(() async { st.close(); if (await tmp.exists()) await tmp.delete(recursive: true); });');
  File(p).writeAsStringSync(s.toString());
  print('Gen1: ${s.length} chars');
}