import 'dart:io';
void main() {
  final p = r'C:\Users\JIM\my_spots\test\services\zone_download_service_test.dart';
  final s = StringBuffer();
  s.writeln("  group('downloadZone — completion states', () {");
  s.writeln("    test('all layers successful → map status ready', () async {");
  s.writeln("      final d = FakeLayerDownloader(results: [");
  s.writeln("        const LayerDownloadResult(downloadedTileCount: 100, estimatedTileCount: 100, successful: true),");
  s.writeln("        const LayerDownloadResult(downloadedTileCount: 50, estimatedTileCount: 50, successful: true),");
  s.writeln("      ]);");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = repo.save(_m('all-ok'));");
  s.writeln("      final a = repo.saveLayer(map, _l(LayerType.marine25k));");
  s.writeln("      final b = repo.saveLayer(map, _l(LayerType.lidarOmbrage));");
  s.writeln("      await s2.downloadZone(map: map, layers: [a, b]);");
  s.writeln("      final u = repo.findByUuid(map.uuid)!;");
  s.writeln("      expect(u.status, OfflineMapStatus.ready);");
  s.writeln("      expect(u.completedAt.millisecondsSinceEpoch, greaterThan(0));");
  s.writeln("      expect(repo.findLayerById(a.id)!.downloadStatus, LayerDownloadStatus.completed);");
  s.writeln("      expect(repo.findLayerById(b.id)!.downloadStatus, LayerDownloadStatus.completed);");
  s.writeln("    });");
  s.writeln("    test('all layers failed → map status failed', () async {");
  s.writeln("      final d = FakeLayerDownloader(results: [");
  s.writeln("        const LayerDownloadResult(downloadedTileCount: 0, estimatedTileCount: 100, successful: false),");
  s.writeln("        const LayerDownloadResult(downloadedTileCount: 0, estimatedTileCount: 50, successful: false),");
  s.writeln("      ]);");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = repo.save(_m('all-fail'));");
  s.writeln("      final a = repo.saveLayer(map, _l(LayerType.marine25k));");
  s.writeln("      final b = repo.saveLayer(map, _l(LayerType.lidarOmbrage));");
  s.writeln("      await s2.downloadZone(map: map, layers: [a, b]);");
  s.writeln("      expect(repo.findByUuid(map.uuid)!.status, OfflineMapStatus.failed);");
  s.writeln("    });");
  s.writeln("    test('mixed results → map status partial', () async {");
  s.writeln("      final d = FakeLayerDownloader(results: [");
  s.writeln("        const LayerDownloadResult(downloadedTileCount: 100, estimatedTileCount: 100, successful: true),");
  s.writeln("        const LayerDownloadResult(downloadedTileCount: 0, estimatedTileCount: 50, successful: false),");
  s.writeln("      ]);");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = repo.save(_m('partial'));");
  s.writeln("      final a = repo.saveLayer(map, _l(LayerType.marine25k));");
  s.writeln("      final b = repo.saveLayer(map, _l(LayerType.lidarOmbrage));");
  s.writeln("      await s2.downloadZone(map: map, layers: [a, b]);");
  s.writeln("      final u = repo.findByUuid(map.uuid)!;");
  s.writeln("      expect(u.status, OfflineMapStatus.partial);");
  s.writeln("      expect(u.completedAt.millisecondsSinceEpoch, greaterThan(0));");
  s.writeln("    });");
  s.writeln("    test('successful layer records tile counts in ObjectBox', () async {");
  s.writeln("      final d = FakeLayerDownloader(results: [");
  s.writeln("        const LayerDownloadResult(downloadedTileCount: 42, estimatedTileCount: 100, successful: true),");
  s.writeln("      ]);");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = repo.save(_m('tile-count'));");
  s.writeln("      final layer = repo.saveLayer(map, _l(LayerType.marine25k));");
  s.writeln("      await s2.downloadZone(map: map, layers: [layer]);");
  s.writeln("      final u = repo.findLayerById(layer.id)!;");
  s.writeln("      expect(u.downloadedTileCount, 42);");
  s.writeln("      expect(u.estimatedTileCount, 100);");
  s.writeln("    });");
  s.writeln("  });");
  File(p).writeAsStringSync(File(p).readAsStringSync() + s.toString(), flush: true);
  print('Gen3: ${s.length} chars');
}