import 'dart:io';
void main() {
  final p = r'C:\Users\JIM\my_spots\test\services\zone_download_service_test.dart';
  final s = StringBuffer();
  s.writeln("  group('downloadZone — cancellation', () {");
  s.writeln("    test('cancelDownload sets map to failed', () async {");
  s.writeln("      final d = FakeLayerDownloader(results: [const LayerDownloadResult(downloadedTileCount: 10, estimatedTileCount: 100, successful: true)]);");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = repo.save(_m('cancel-fail')); final layer = repo.saveLayer(map, _l(LayerType.marine25k));");
  s.writeln("      unawaited(s2.downloadZone(map: map, layers: [layer]));");
  s.writeln("      await Future.delayed(Duration.zero); await s2.cancelDownload(map.uuid);");
  s.writeln("      await Future.delayed(Duration.zero);");
  s.writeln("      expect(repo.findByUuid(map.uuid)!.status, OfflineMapStatus.failed);");
  s.writeln("    });");
  s.writeln("    test('cancelDownload delegates zone uuid to downloader', () async {");
  s.writeln("      final d = FakeLayerDownloader(); final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      await s2.cancelDownload('cancel-uuid');");
  s.writeln("      expect(d.cancelledZone, 'cancel-uuid');");
  s.writeln("    });");
  s.writeln("    test('cancel on inactive zone is safe no-op', () async {");
  s.writeln("      final d = FakeLayerDownloader(); final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      await s2.cancelDownload('never-active'); // must not throw");
  s.writeln("    });");
  s.writeln("  });");
  s.writeln("  group('downloadZone — store routing', () {");
  s.writeln("    test('marine25k uses marine_zone_ uuid store', () async {");
  s.writeln("      final d = FakeLayerDownloader(); final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = repo.save(_m('marine-store')); final layer = repo.saveLayer(map, _l(LayerType.marine25k));");
  s.writeln("      await s2.downloadZone(map: map, layers: [layer]);");
  s.writeln("      expect(d.calls.single.sn, 'marine_zone_\${map.uuid}');");
  s.writeln("    });");
  s.writeln("    test('lidarOmbrage uses lidar_zone_ uuid store', () async {");
  s.writeln("      final d = FakeLayerDownloader(); final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = repo.save(_m('lidar-store')); final layer = repo.saveLayer(map, _l(LayerType.lidarOmbrage));");
  s.writeln("      await s2.downloadZone(map: map, layers: [layer]);");
  s.writeln("      expect(d.calls.single.sn, 'lidar_zone_\${map.uuid}');");
  s.writeln("    });");
  s.writeln("  });");
  File(p).writeAsStringSync(File(p).readAsStringSync() + s.toString(), flush: true);
  print('Gen4a: ${s.length} chars');
}