import 'dart:io';
void main() {
  final p = r'C:\Users\JIM\my_spots\test\services\zone_download_service_test.dart';
  final s = StringBuffer();
  s.writeln('');
  s.writeln("  group('downloadZone — URL routing', () {");
  s.writeln("    test('marine10k URL contains RASTER_MARINE_10_WMTS_3857', () async {");
  s.writeln("      final d = FakeLayerDownloader();");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = _m('url-10k'); repo.save(map);");
  s.writeln("      final layer = _l(LayerType.marine10k); repo.saveLayer(map, layer);");
  s.writeln("      await s2.downloadZone(map: map, layers: [layer]);");
  s.writeln("      expect(d.calls.single.u, contains('RASTER_MARINE_10_WMTS_3857'));");
  s.writeln("    });");
  s.writeln("    test('marine50k URL contains RASTER_MARINE_50_WMTS_3857', () async {");
  s.writeln("      final d = FakeLayerDownloader();");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = _m('url-50k'); repo.save(map);");
  s.writeln("      final layer = _l(LayerType.marine50k); repo.saveLayer(map, layer);");
  s.writeln("      await s2.downloadZone(map: map, layers: [layer]);");
  s.writeln("      expect(d.calls.single.u, contains('RASTER_MARINE_50_WMTS_3857'));");
  s.writeln("    });");
  s.writeln("    test('lidar URL contains LIDAR_OMBRAGE_WMTS', () async {");
  s.writeln("      final d = FakeLayerDownloader();");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = _m('url-lidar'); repo.save(map);");
  s.writeln("      final layer = _l(LayerType.lidarOmbrage); repo.saveLayer(map, layer);");
  s.writeln("      await s2.downloadZone(map: map, layers: [layer]);");
  s.writeln("      expect(d.calls.single.u, contains('LIDAR_OMBRAGE_WMTS'));");
  s.writeln("    });");
  s.writeln("    test('zoom range forwarded from layer', () async {");
  s.writeln("      final d = FakeLayerDownloader();");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = _m('zoom'); repo.save(map);");
  s.writeln("      final layer = _l(LayerType.marine25k);");
  s.writeln("      layer.minZoom = 12; layer.maxZoom = 18;");
  s.writeln("      repo.saveLayer(map, layer);");
  s.writeln("      await s2.downloadZone(map: map, layers: [layer]);");
  s.writeln("      expect(d.calls.single.zmin, 12); expect(d.calls.single.zmax, 18);");
  s.writeln("    });");
  s.writeln("  });");
  s.writeln("  group('onProgress callback', () {");
  s.writeln("    test('receives layer labels for each layer', () async {");
  s.writeln("      final d = FakeLayerDownloader(results: [");
  s.writeln("        const LayerDownloadResult(downloadedTileCount: 10, estimatedTileCount: 10, successful: true),");
  s.writeln("        const LayerDownloadResult(downloadedTileCount: 5, estimatedTileCount: 5, successful: true),");
  s.writeln("      ]);");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = _m('progress'); repo.save(map);");
  s.writeln("      final a = _l(LayerType.marine25k); final b = _l(LayerType.lidarOmbrage);");
  s.writeln("      repo.saveLayer(map, a); repo.saveLayer(map, b);");
  s.writeln("      final labels = <String>[];");
  s.writeln("      await s2.downloadZone(map: map, layers: [a, b],");
  s.writeln("        onProgress: ({required progress, required layerLabel}) { labels.add(layerLabel); });");
  s.writeln("      expect(labels, containsAll(['marine25k', 'lidarOmbrage']));");
  s.writeln("    });");
  s.writeln("  });");
  s.writeln("  group('isDownloading / activeCount', () {");
  s.writeln("    test('isDownloading true during active download', () async {");
  s.writeln("      final d = FakeLayerDownloader(results: [const LayerDownloadResult(downloadedTileCount: 10, estimatedTileCount: 10, successful: true)]);");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = _m('is-dl'); repo.save(map);");
  s.writeln("      final layer = _l(LayerType.marine25k); repo.saveLayer(map, layer);");
  s.writeln("      expect(s2.isDownloading(map.uuid), isFalse);");
  s.writeln("      unawaited(s2.downloadZone(map: map, layers: [layer]));");
  s.writeln("      await Future.delayed(Duration.zero);");
  s.writeln("      expect(s2.isDownloading(map.uuid), isTrue);");
  s.writeln("      await Future.delayed(Duration.zero);");
  s.writeln("    });");
  s.writeln("    test('activeCount is 1 during download', () async {");
  s.writeln("      final d = FakeLayerDownloader(results: [const LayerDownloadResult(downloadedTileCount: 10, estimatedTileCount: 10, successful: true)]);");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = _m('active'); repo.save(map);");
  s.writeln("      final layer = _l(LayerType.marine25k); repo.saveLayer(map, layer);");
  s.writeln("      expect(s2.activeCount, 0);");
  s.writeln("      unawaited(s2.downloadZone(map: map, layers: [layer]));");
  s.writeln("      await Future.delayed(Duration.zero);");
  s.writeln("      expect(s2.activeCount, 1);");
  s.writeln("      await Future.delayed(Duration.zero);");
  s.writeln("    });");
  s.writeln("  });");
  s.writeln("}");
  File(p).writeAsStringSync(File(p).readAsStringSync() + s.toString() + '\n', flush: true);
  print('ztg_d2 done: ${s.length} chars');
}