import 'dart:io';
void main() {
  final p = r'C:\Users\JIM\my_spots\test\services\zone_download_service_test.dart';
  final lines = <String>[];
  void w(String s) => lines.add(s);

  w('// Unit tests for ZoneDownloadService — zone-scoped FMTC download orchestration.');
  w('//');
  w('// NOTE: Uses an in-memory FakeMapLayerRepository instead of ObjectBox');
  w('// (pre-existing objectbox.dll unavailable in test PATH).');
  w('');
  w("import 'dart:async';");
  w("import 'package:flutter_map/flutter_map.dart';");
  w("import 'package:flutter_map_tile_caching/flutter_map_tile_caching.dart';");
  w("import 'package:flutter_test/flutter_test.dart';");
  w("import 'package:my_spots/models/offline_map.dart';");
  w("import 'package:my_spots/models/offline_map_layer.dart';");
  w("import 'package:my_spots/services/zone_download_service.dart';");
  w('');
  w('// In-memory fake: replaces OfflineMapRepository so tests avoid ObjectBox.');
  w('class FakeMapLayerRepository implements MapLayerRepository {');
  w('  final maps = <String, OfflineMap>{}; // keyed by uuid');
  w('  final layers = <int, OfflineMapLayer>{}; // keyed by ObjectBox-assigned id');
  w('  int _nextMapId = 1;');
  w('  int _nextLayerId = 1;');
  w('');
  w('  @override');
  w('  void save(OfflineMap map) {');
  w('    map.id = _nextMapId++;');
  w("    maps[map.uuid] = map;");
  w('  }');
  w('');
  w('  @override');
  w('  void saveLayer(OfflineMap map, OfflineMapLayer layer) {');
  w('    layer.offlineMapId = map.id;');
  w('    layer.id = _nextLayerId++;');
  w("    layers[layer.id] = layer;");
  w('  }');
  w('');
  w('  @override');
  w('  OfflineMap? findByUuid(String uuid) => maps[uuid];');
  w('');
  w('  @override');
  w('  OfflineMapLayer? findLayerById(int id) => layers[id];');
  w('}');
  w('');
  w('// Fake downloader that records calls and returns configurable results.');
  w('class FakeLayerDownloader implements LayerDownloader {');
  w('  FakeLayerDownloader({this.results = const [], this.cancelError});');
  w('  final List<LayerDownloadResult> results;');
  w('  final Object? cancelError;');
  w('  final calls = <_Call>[];');
  w('  String? cancelledZone;');
  w('  int count = 0;');
  w('  @override');
  w('  Future<LayerDownloadResult> downloadLayer({');
  w('    required String zoneUuid, required FMTCStore store,');
  w('    required String urlTemplate, required LatLngBounds bounds,');
  w('    required int minZoom, required int maxZoom,');
  w('    required Map<String, String> headers,');
  w('    required void Function(double) onProgress,');
  w('  }) async {');
  w('    calls.add(_Call(z: zoneUuid, sn: store.storeName, u: urlTemplate,');
  w('        zmin: minZoom, zmax: maxZoom));');
  w('    count++;');
  w('    onProgress(1.0);');
  w('    if (count <= results.length) return results[count - 1];');
  w('    return const LayerDownloadResult(downloadedTileCount: 0, estimatedTileCount: 0, successful: true);');
  w('  }');
  w('  @override');
  w('  Future<void> cancel(String zoneUuid) async {');
  w('    cancelledZone = zoneUuid;');
  w("    if (cancelError != null) throw StateError('cancel-fail');");
  w('  }');
  w('  @override void pause(String z) {}');
  w('  @override void resume(String z) {}');
  w('}');
  w('');
  w('class _Call {');
  w('  _Call({required this.z, required this.sn, required this.u, required this.zmin, required this.zmax});');
  w('  final String z, sn, u;');
  w('  final int zmin, zmax;');
  w('}');
  w('');
  w('OfflineMap _m(String u) => OfflineMap.create(uuid: u, name: \'Z\', northLat: 44, southLat: 43, westLng: 6, eastLng: 7);');
  w('OfflineMapLayer _l(LayerType t) => OfflineMapLayer.create(layerType: t, minZoom: 8, maxZoom: 14);');
  w('');
  w('void main() {');
  w('  late FakeMapLayerRepository repo;');
  w('');
  w('  setUp(() { repo = FakeMapLayerRepository(); });');

  File(p).writeAsStringSync(lines.join('\n'));
  print('ztg_a done: ${lines.length} lines');
}