import 'dart:io';
void main() {
  final p = r'C:\Users\JIM\my_spots\test\services\zone_download_service_test.dart';
  final s = StringBuffer();
  s.writeln('');
  s.writeln("  group('downloadZone — completion states', () {");
  s.writeln("    test('all layers successful → map status ready', () async {");
  s.writeln("      final d = FakeLayerDownloader(results: [");
  s.writeln("        const LayerDownloadResult(downloadedTileCount: 100, estimatedTileCount: 100, successful: true),");
  s.writeln("        const LayerDownloadResult(downloadedTileCount: 50, estimatedTileCount: 50, successful: true),");
  s.writeln("      ]);");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = _m('all-ok'); repo.save(map);");
  s.writeln("      final a = _l(LayerType.marine25k); final b = _l(LayerType.lidarOmbrage);");
  s.writeln("      repo.saveLayer(map, a); repo.saveLayer(map, b);");
  s.writeln("      await s2.downloadZone(map: map, layers: [a, b]);");
  s.writeln("      final u = repo.findByUuid(map.uuid)!;");
  s.writeln("      expect(u.status, OfflineMapStatus.ready);");
  s.writeln("      expect(u.completedAt.millisecondsSinceEpoch, greaterThan(0));");
  s.writeln("      expect(repo.findLayerById(a.id)!.downloadStatus, LayerDownloadStatus.completed);");
  s.writeln("      expect(repo.findLayerById(b.id)!.downloadStatus, LayerDownloadStatus.completed);");
  s.writeln("    });");
  s.writeln("    test('all layers failed → map status failed', () async {");
  s.writeln("      final d = FakeLayerDownloader(results: [");
  s.writeln("        const LayerDownloadResult(downloadedTileCount: 0, estimatedTileCount: 100, successful: false),");
  s.writeln("        const LayerDownloadResult(downloadedTileCount: 0, estimatedTileCount: 50, successful: false),");
  s.writeln("      ]);");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = _m('all-fail'); repo.save(map);");
  s.writeln("      final a = _l(LayerType.marine25k); final b = _l(LayerType.lidarOmbrage);");
  s.writeln("      repo.saveLayer(map, a); repo.saveLayer(map, b);");
  s.writeln("      await s2.downloadZone(map: map, layers: [a, b]);");
  s.writeln("      expect(repo.findByUuid(map.uuid)!.status, OfflineMapStatus.failed);");
  s.writeln("    });");
  s.writeln("    test('mixed results → map status partial', () async {");
  s.writeln("      final d = FakeLayerDownloader(results: [");
  s.writeln("        const LayerDownloadResult(downloadedTileCount: 100, estimatedTileCount: 100, successful: true),");
  s.writeln("        const LayerDownloadResult(downloadedTileCount: 0, estimatedTileCount: 50, successful: false),");
  s.writeln("      ]);");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = _m('partial'); repo.save(map);");
  s.writeln("      final a = _l(LayerType.marine25k); final b = _l(LayerType.lidarOmbrage);");
  s.writeln("      repo.saveLayer(map, a); repo.saveLayer(map, b);");
  s.writeln("      await s2.downloadZone(map: map, layers: [a, b]);");
  s.writeln("      final u = repo.findByUuid(map.uuid)!;");
  s.writeln("      expect(u.status, OfflineMapStatus.partial);");
  s.writeln("      expect(u.completedAt.millisecondsSinceEpoch, greaterThan(0));");
  s.writeln("    });");
  s.writeln("    test('successful layer records tile counts in fake repo', () async {");
  s.writeln("      final d = FakeLayerDownloader(results: [const LayerDownloadResult(downloadedTileCount: 42, estimatedTileCount: 100, successful: true)]);");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = _m('tile-count'); repo.save(map);");
  s.writeln("      final layer = _l(LayerType.marine25k); repo.saveLayer(map, layer);");
  s.writeln("      await s2.downloadZone(map: map, layers: [layer]);");
  s.writeln("      final u = repo.findLayerById(layer.id)!;");
  s.writeln("      expect(u.downloadedTileCount, 42);");
  s.writeln("      expect(u.estimatedTileCount, 100);");
  s.writeln("    });");
  s.writeln("  });");
  File(p).writeAsStringSync(File(p).readAsStringSync() + s.toString(), flush: true);
  print('ztg_c done: ${s.length} chars');
}