import 'dart:io';
void main() {
  final p = r'C:\Users\JIM\my_spots\test\services\zone_download_service_test.dart';
  final s = StringBuffer();
  s.writeln('');
  s.writeln("  group('downloadZone — empty input', () {");
  s.writeln("    test('empty layers list returns without calling downloader', () async {");
  s.writeln("      final d = FakeLayerDownloader();");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = _m('empty'); repo.save(map);");
  s.writeln("      await s2.downloadZone(map: map, layers: []);");
  s.writeln("      expect(d.count, 0);");
  s.writeln("    });");
  s.writeln("  });");
  s.writeln('');
  s.writeln("  group('downloadZone — initial state', () {");
  s.writeln("    test('sets map status to downloading before completion', () async {");
  s.writeln("      final d = FakeLayerDownloader();");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = _m('init-map'); repo.save(map);");
  s.writeln("      final layer = _l(LayerType.marine25k);");
  s.writeln("      // Save layer to assign an id, then pass to service.");
  s.writeln("      repo.saveLayer(map, layer);");
  s.writeln("      unawaited(s2.downloadZone(map: map, layers: [layer]));");
  s.writeln("      await Future.delayed(Duration.zero);");
  s.writeln("      expect(repo.findByUuid(map.uuid)!.status, OfflineMapStatus.downloading);");
  s.writeln("      await s2.cancelDownload(map.uuid);");
  s.writeln("    });");
  s.writeln("    test('sets all layer statuses to downloading', () async {");
  s.writeln("      final d = FakeLayerDownloader();");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = _m('init-layers'); repo.save(map);");
  s.writeln("      final a = _l(LayerType.marine25k);");
  s.writeln("      final b = _l(LayerType.lidarOmbrage);");
  s.writeln("      repo.saveLayer(map, a); repo.saveLayer(map, b);");
  s.writeln("      unawaited(s2.downloadZone(map: map, layers: [a, b]));");
  s.writeln("      await Future.delayed(Duration.zero);");
  s.writeln("      expect(repo.findLayerById(a.id)!.downloadStatus, LayerDownloadStatus.downloading);");
  s.writeln("      expect(repo.findLayerById(b.id)!.downloadStatus, LayerDownloadStatus.downloading);");
  s.writeln("      await s2.cancelDownload(map.uuid);");
  s.writeln("    });");
  s.writeln("  });");
  File(p).writeAsStringSync(File(p).readAsStringSync() + s.toString(), flush: true);
  print('ztg_b done: ${s.length} chars');
}