import 'dart:io';
void main() {
  final p = r'C:\Users\JIM\my_spots\test\services\zone_download_service_test.dart';
  final s = StringBuffer();
  s.writeln('');
  s.writeln("  group('downloadZone — cancellation', () {");
  s.writeln("    test('cancelDownload sets map to failed', () async {");
  s.writeln("      final d = FakeLayerDownloader(results: [const LayerDownloadResult(downloadedTileCount: 10, estimatedTileCount: 100, successful: true)]);");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = _m('cancel-fail'); repo.save(map);");
  s.writeln("      final layer = _l(LayerType.marine25k); repo.saveLayer(map, layer);");
  s.writeln("      unawaited(s2.downloadZone(map: map, layers: [layer]));");
  s.writeln("      await Future.delayed(Duration.zero);");
  s.writeln("      await s2.cancelDownload(map.uuid);");
  s.writeln("      await Future.delayed(Duration.zero);");
  s.writeln("      expect(repo.findByUuid(map.uuid)!.status, OfflineMapStatus.failed);");
  s.writeln("    });");
  s.writeln("    test('cancelDownload delegates zone uuid to downloader', () async {");
  s.writeln("      final d = FakeLayerDownloader();");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      await s2.cancelDownload('cancel-uuid');");
  s.writeln("      expect(d.cancelledZone, 'cancel-uuid');");
  s.writeln("    });");
  s.writeln("    test('cancel on inactive zone is safe no-op', () async {");
  s.writeln("      final d = FakeLayerDownloader();");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      await s2.cancelDownload('never-active'); // must not throw");
  s.writeln("    });");
  s.writeln("  });");
  s.writeln("  group('downloadZone — store routing', () {");
  s.writeln("    test('marine25k uses marine_zone_ uuid store', () async {");
  s.writeln("      final d = FakeLayerDownloader();");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = _m('marine-store'); repo.save(map);");
  s.writeln("      final layer = _l(LayerType.marine25k); repo.saveLayer(map, layer);");
  s.writeln("      await s2.downloadZone(map: map, layers: [layer]);");
  s.writeln("      expect(d.calls.single.sn, 'marine_zone_\${map.uuid}');");
  s.writeln("    });");
  s.writeln("    test('lidarOmbrage uses lidar_zone_ uuid store', () async {");
  s.writeln("      final d = FakeLayerDownloader();");
  s.writeln("      final s2 = ZoneDownloadService(repository: repo, downloader: d);");
  s.writeln("      final map = _m('lidar-store'); repo.save(map);");
  s.writeln("      final layer = _l(LayerType.lidarOmbrage); repo.saveLayer(map, layer);");
  s.writeln("      await s2.downloadZone(map: map, layers: [layer]);");
  s.writeln("      expect(d.calls.single.sn, 'lidar_zone_\${map.uuid}');");
  s.writeln("    });");
  s.writeln("  });");
  File(p).writeAsStringSync(File(p).readAsStringSync() + s.toString(), flush: true);
  print('ztg_d1 done: ${s.length} chars');
}