// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/offline_map.dart';
import 'models/offline_map_layer.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5182520997279946803),
    name: 'OfflineMapLayer',
    lastPropertyId: const obx_int.IdUid(8, 665590391856139998),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 922587658472003169),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 256897108380192436),
        name: 'offlineMapId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2482675901880860640),
        name: 'layerTypeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5112291591954589995),
        name: 'minZoom',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8342025355646786947),
        name: 'maxZoom',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1477336916736815939),
        name: 'statusIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5558319306818141683),
        name: 'estimatedTileCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 665590391856139998),
        name: 'downloadedTileCount',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5621580101653289067),
    name: 'OfflineMap',
    lastPropertyId: const obx_int.IdUid(11, 5526990479795015572),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2442507201481088472),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7460004151515988256),
        name: 'uuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6263178554942586765),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7610148528282434889),
        name: 'northLat',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4281449343890196518),
        name: 'southLat',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2563115367669983531),
        name: 'westLng',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4084698283543616286),
        name: 'eastLng',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8961617604869378169),
        name: 'statusIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4604877508117257081),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5526990479795015572),
        name: 'completedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 5621580101653289067),
    lastIndexId: const obx_int.IdUid(1, 8228622745366417356),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [8228622745366417356],
    retiredPropertyUids: const [8365270913800956856],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    OfflineMapLayer: obx_int.EntityDefinition<OfflineMapLayer>(
      model: _entities[0],
      toOneRelations: (OfflineMapLayer object) => [],
      toManyRelations: (OfflineMapLayer object) => {},
      getId: (OfflineMapLayer object) => object.id,
      setId: (OfflineMapLayer object, int id) {
        object.id = id;
      },
      objectToFB: (OfflineMapLayer object, fb.Builder fbb) {
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.offlineMapId);
        fbb.addInt64(2, object.layerTypeIndex);
        fbb.addInt64(3, object.minZoom);
        fbb.addInt64(4, object.maxZoom);
        fbb.addInt64(5, object.statusIndex);
        fbb.addInt64(6, object.estimatedTileCount);
        fbb.addInt64(7, object.downloadedTileCount);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final offlineMapIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final layerTypeIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final minZoomParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final maxZoomParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final statusIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final estimatedTileCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final downloadedTileCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final object = OfflineMapLayer(
          id: idParam,
          offlineMapId: offlineMapIdParam,
          layerTypeIndex: layerTypeIndexParam,
          minZoom: minZoomParam,
          maxZoom: maxZoomParam,
          statusIndex: statusIndexParam,
          estimatedTileCount: estimatedTileCountParam,
          downloadedTileCount: downloadedTileCountParam,
        );

        return object;
      },
    ),
    OfflineMap: obx_int.EntityDefinition<OfflineMap>(
      model: _entities[1],
      toOneRelations: (OfflineMap object) => [],
      toManyRelations: (OfflineMap object) => {},
      getId: (OfflineMap object) => object.id,
      setId: (OfflineMap object, int id) {
        object.id = id;
      },
      objectToFB: (OfflineMap object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addFloat64(3, object.northLat);
        fbb.addFloat64(4, object.southLat);
        fbb.addFloat64(5, object.westLng);
        fbb.addFloat64(6, object.eastLng);
        fbb.addInt64(7, object.statusIndex);
        fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(10, object.completedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final northLatParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final southLatParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final westLngParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final eastLngParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final statusIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final completedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0),
        );
        final object = OfflineMap(
          id: idParam,
          uuid: uuidParam,
          name: nameParam,
          northLat: northLatParam,
          southLat: southLatParam,
          westLng: westLngParam,
          eastLng: eastLngParam,
          statusIndex: statusIndexParam,
          createdAt: createdAtParam,
          completedAt: completedAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [OfflineMapLayer] entity fields to define ObjectBox queries.
class OfflineMapLayer_ {
  /// See [OfflineMapLayer.id].
  static final id = obx.QueryIntegerProperty<OfflineMapLayer>(
    _entities[0].properties[0],
  );

  /// See [OfflineMapLayer.offlineMapId].
  static final offlineMapId = obx.QueryIntegerProperty<OfflineMapLayer>(
    _entities[0].properties[1],
  );

  /// See [OfflineMapLayer.layerTypeIndex].
  static final layerTypeIndex = obx.QueryIntegerProperty<OfflineMapLayer>(
    _entities[0].properties[2],
  );

  /// See [OfflineMapLayer.minZoom].
  static final minZoom = obx.QueryIntegerProperty<OfflineMapLayer>(
    _entities[0].properties[3],
  );

  /// See [OfflineMapLayer.maxZoom].
  static final maxZoom = obx.QueryIntegerProperty<OfflineMapLayer>(
    _entities[0].properties[4],
  );

  /// See [OfflineMapLayer.statusIndex].
  static final statusIndex = obx.QueryIntegerProperty<OfflineMapLayer>(
    _entities[0].properties[5],
  );

  /// See [OfflineMapLayer.estimatedTileCount].
  static final estimatedTileCount = obx.QueryIntegerProperty<OfflineMapLayer>(
    _entities[0].properties[6],
  );

  /// See [OfflineMapLayer.downloadedTileCount].
  static final downloadedTileCount = obx.QueryIntegerProperty<OfflineMapLayer>(
    _entities[0].properties[7],
  );
}

/// [OfflineMap] entity fields to define ObjectBox queries.
class OfflineMap_ {
  /// See [OfflineMap.id].
  static final id = obx.QueryIntegerProperty<OfflineMap>(
    _entities[1].properties[0],
  );

  /// See [OfflineMap.uuid].
  static final uuid = obx.QueryStringProperty<OfflineMap>(
    _entities[1].properties[1],
  );

  /// See [OfflineMap.name].
  static final name = obx.QueryStringProperty<OfflineMap>(
    _entities[1].properties[2],
  );

  /// See [OfflineMap.northLat].
  static final northLat = obx.QueryDoubleProperty<OfflineMap>(
    _entities[1].properties[3],
  );

  /// See [OfflineMap.southLat].
  static final southLat = obx.QueryDoubleProperty<OfflineMap>(
    _entities[1].properties[4],
  );

  /// See [OfflineMap.westLng].
  static final westLng = obx.QueryDoubleProperty<OfflineMap>(
    _entities[1].properties[5],
  );

  /// See [OfflineMap.eastLng].
  static final eastLng = obx.QueryDoubleProperty<OfflineMap>(
    _entities[1].properties[6],
  );

  /// See [OfflineMap.statusIndex].
  static final statusIndex = obx.QueryIntegerProperty<OfflineMap>(
    _entities[1].properties[7],
  );

  /// See [OfflineMap.createdAt].
  static final createdAt = obx.QueryDateProperty<OfflineMap>(
    _entities[1].properties[8],
  );

  /// See [OfflineMap.completedAt].
  static final completedAt = obx.QueryDateProperty<OfflineMap>(
    _entities[1].properties[9],
  );
}
